language: node_js

node_js:
  - 6
  - 8

matrix:
  fast_finish: true

before_install:
  - npm --version

notifications:
  email: false
  slack:
    secure: aurtUgL9JMlqnYcgGcE5FWigEI8gRpu1uL5Na2qxXVpbVCn09d4YQf1a0bvCcR8czjhFoMLpEjYYwW17tZVRO0DuZrBZaHR3k8VIKcTjYndJcgH4fmDR1Og9DudO/yB1l7pPrIrhp7rLZN+bYKgl9mDQgPJlQQP5WLkaY8do2Y3r/ZzMQV4127vllHkhIB+YSgQk8RqUy3+rLD5+J9BukNGrcEBkZ8O0EkqVgauKzv2NjIsGQ3gWIXNi6FLOTxMka920Wvs1QHxQQHOlzUfaMasEH8Ha+LnqTP0V03oyu0+iVlW1BiWpnD4CBQCRvfktNWUf5QiPsuVKN/USdoys2wc1j5bXiF2mjPeGYUD4FbyamJlpVytuoKpj1hZTO3fWJm8vvi3fDP16G4nMY12I3aXlLg35Fmvdadw7RAZRuWD+ny8EAieAKzSykNP+1q7KwiGkmyQ8OgSKhaPGM8QmyEUtFaJELWPCNPIYY61uzODxtpGr2FMePzlFDf43CYXY41j1w5PzZfjqgkfSpD3FOWzxlZtKygNBZX3E7OdDzki0rsB/JXtDwoKkPnY94xcujwP9UkKLbeeyxndcOjGaRfHVrxoulLg8g+gd3JATC5rsgaE/TgOFJALoDiaKYAKOSnvYemXSaDwNTOp8jQYEurURxTyANLc2uwGLuC/xmA8=

cache:
  directories:
  - $HOME/.npm
