language: node_js

node_js:
  - 6
  - 8

matrix:
  fast_finish: true

before_install:
- npm --version

notifications:
  email: false
  slack:
    secure: GT7dF1vvMhGoh2flLphIrJDCYCSGXYllDw7oXlWAOcsZExLY9S4dNk/jFDWDsOhqVeJuDcM+27Wb6A9I+tLZxd5AgbKoSG45vMg9fJoZKNm+jTjZq1lpDMeOBszAkJUQGzfL/chkxoTn88o/o/QGvEDqPmmP5mwpehVIKw1APf95x6OxM2kVD2qKFsHbAMv/wg/U7kC3Vh+qX8OCu+rGfftAZw7cbISpZnKGIvmBmmi9vXp3NrQV3BT14eNniNI2vuMGuD1W64CEZgt64dqwchsqaZJmi5hSgNW50J3IZLEDWqu8AkrfIC0mfMYY5Te3j8YThfkcMZ9Okfkt/yyQEIiTxIWQjCgq5JwHFKwPlys5xS6z1mGEgMHinGdMnP2ouancdiXlHlZbH+BNbdypUjkcxWp0bvQQ5d6/udm8yHzel4JXXd5vorhP72gbaCkCY6z3A8wBppEbnq0uayPCo6QNRmI0B6dgIZsiomA6vh0M4RO9eK6tvfXrWmVnBJFECdTyDHZkuVX8J804pBTFhGj9lC91y3s0kZibF41IIz2cs5SIRGthp/na6WoI8jYQnBdOAmq5MxQZTdSSmOo9Ab3fvK+dFb9imUW+PdqNRkbKQTXjRSBMxWINMtet0XSPpJ96EtaxBfTE1DeISOyBI1SUzzcW/uGnlcpk/EcTfbU=

cache:
  directories:
    - "$HOME/.npm"
